name: expo_bike
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.4.0
  carousel_slider: ^2.1.0
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_logo.png
    - assets/images/user_icon.png
    - assets/images/security_icon.png
    - assets/images/facebook_icon.png
    - assets/images/google_icon.png
    - assets/images/close_icon.png
    - assets/images/bicycle.png
    - assets/images/check_icon.png

    - assets/images/explorar_icon.png
    - assets/images/zonas_icon.png
    - assets/images/expo_icon.png
    - assets/images/rutas_icon.png
    - assets/images/cuenta_icon.png

    - assets/images/explorar_red_icon.png
    - assets/images/zonas_red_icon.png
    - assets/images/expo_red_icon.png
    - assets/images/rutas_red_icon.png
    - assets/images/cuenta_red_icon.png

    - assets/images/main_splash.png
    - assets/images/main_splash_logo.png

    - assets/images/amigos_icon.png
    - assets/images/settings_red_icon.png
    - assets/images/user_avatar.png
    - assets/images/crown_red.png
    - assets/images/equipo_icon.png
    - assets/images/eventos_icon.png
    - assets/images/estadisticas_icon.png
    - assets/images/favoritos_icon.png
    - assets/images/right_icon.png
    - assets/images/vertical_line.png

    - assets/images/left_icon.png
    - assets/images/notification_icon.png
    - assets/images/message_icon.png
    - assets/images/star_icon.png
    - assets/images/sign_out_icon.png

    - assets/images/explorar_tab_logo.png
    - assets/images/rectangle_grey.png
    - assets/images/favoritos_background_icon.png
    - assets/images/explorar_inscribirme_background.png
    - assets/images/explorar_inscribirme_information_icon.png
    - assets/images/explorar_ubicaciones_message_icon.png
    - assets/images/map_circle_icon.png
    - assets/images/explorar_ubicaciones_search_icon.png
    - assets/images/explorar_ubicaciones_menu_icon.png
    - assets/images/filter_first_icon.png
    - assets/images/filter_second_icon.png
    - assets/images/filter_third_icon.png
    - assets/images/filter_fourth_icon.png
    - assets/images/checkbox_true_icon.png
    - assets/images/checkbox_false_icon.png

    - assets/images/zonas_san_icon.png
    - assets/images/zonas_cartago_icon.png
    - assets/images/zonas_heredia_icon.png
    - assets/images/zonas_alajuela.png
    - assets/images/zonas_guanacaste_icon.png
    - assets/images/zonas_puntarenas_icon.png
    - assets/images/zonas_limon_icon.png
    - assets/images/zonas_park.png
    - assets/images/zonas_ciclos.png
    - assets/images/zonas_star_icon.png
    - assets/images/zonas_star_red_icon.png
    - assets/images/zonas_trail_icon.png
    - assets/images/zonas_elevation_icon.png
    - assets/images/zonas_grade_icon.png

    - assets/images/expo_slider.png

    - assets/images/rutas_fly_icon.png
    - assets/images/rutas_user_icon.png
    - assets/images/rutas_search_icon.png
    - assets/images/rutas_dialog_logo.png
    - assets/images/rutas_dialog_user_icon.png
    - assets/images/rutas_sos_icon.png
    - assets/images/rutas_share_icon.png
    - assets/images/rutas_vertical_line.png
    - assets/images/rutas_whatsapp_icon.png
    - assets/images/rutas_facebook_icon.png
    - assets/images/rutas_twitter_icon.png
    - assets/images/rutas_instagram_icon.png
    - assets/images/rutas_copiarlink_icon.png
    - assets/images/bottom_icon.png

  fonts:
    - family: HelveticaBold
      fonts:
        - asset: assets/fonts/Helvetica-Bold-Font.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
